apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  description: "The User service that does user stuff."
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: engineering
